# version: "3.7"

# services:
#   # mariadb:
#   #   image: docker.io/mariadb:10.6
#   #   platform: linux/amd64
#   #   command:
#   #     - --character-set-server=utf8mb4
#   #     - --collation-server=utf8mb4_unicode_ci
#   #     - --skip-character-set-client-handshake
#   #     - --skip-innodb-read-only-compressed
#   #   environment:
#   #     MYSQL_ROOT_PASSWORD: admin
#   #     MYSQL_USER: frappe
#   #     MYSQL_PASSWORD: admin
#   #     MYSQL_DATABASE: frappe
#   #   volumes:
#   #     - mariadb-data:/var/lib/mysql

#   mariadb:
#   image: mariadb:10.6
#   environment:
#     - MYSQL_ROOT_PASSWORD=root
#   volumes:
#     - mariadb_data:/var/lib/mysql
#   restart: unless-stopped
#   ports:
#   - "3307:3306"  # map host port 3307 to container 3306



#   # redis_cache:
#   #   image: docker.io/redis:alpine
#   #   platform: linux/amd64

#   # redis_queue:
#   #   image: docker.io/redis:alpine
#   #   platform: linux/amd64

#   # redis-socketio:
#   # image: redis:6.2-alpine  
#   # restart: unless-stopped

#   redis-cache:
#   image: redis:6.2-alpine
#   restart: unless-stopped

# redis-queue:
#   image: redis:6.2-alpine
#   restart: unless-stopped

# redis-socketio:
#   image: redis:6.2-alpine
#   restart: unless-stopped



# # frontend:
# #   image: frappe/erpnext:version-14
# #   ports:
# #     - "8000:8080"   # host:container


#   frappe:
#     image: docker.io/frappe/bench:latest
#     platform: linux/amd64
#     command: sleep infinity
#     environment:
#       SHELL: /bin/bash
#     volumes:
#       - ..:/workspace:cached
#     working_dir: /workspace/development
#     ports:
#       - "8000:8080"


# volumes:
#   mariadb-data:




version: "3.7"

services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3307:3306"

  redis-cache:
    image: redis:6.2-alpine
    restart: unless-stopped

  redis-queue:
    image: redis:6.2-alpine
    restart: unless-stopped

  redis-socketio:
    image: redis:6.2-alpine
    restart: unless-stopped

  backend:
    image: frappe/erpnext:version-14
    environment:
      FRAPPE_SITE_NAME: mysite.localhost
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sites:/workspace/development/sites:cached

    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  frontend:
    image: frappe/erpnext:version-14
    ports:
      - "8000:8080"
    depends_on:
      - backend

volumes:
  mariadb_data:
